// Generated by Outstatic - do not edit manually
import type { OstDocument } from 'outstatic'

export interface AboutFields {
  bannerImage?: string
  bannerLabel?: string
  introTitle?: string
  introParagraph?: string
  bodyParagraph?: string
}

export interface About extends OstDocument<AboutFields> {}

export type AboutField = keyof About
