// Generated by Outstatic - do not edit manually
import type { OstDocument } from 'outstatic'

export interface ContactFields {
  bannerImage?: string
  bannerLabel?: string
  pageTitle?: string
  pageSubtitle?: string
  emailLabel?: string
  emailAddress?: string
  ctaLabel?: string
}

export interface Contact extends OstDocument<ContactFields> {}

export type ContactField = keyof Contact
