// Generated by Outstatic - do not edit manually
import type { OstDocument } from 'outstatic'

export interface EventsFields {
  bannerImage?: string
  bannerLabel?: string
  pageTitle?: string
  pageSubtitle?: string
}

export interface Events extends OstDocument<EventsFields> {}

export type EventsField = keyof Events
