// Generated by Outstatic - do not edit manually
import type { OstDocument } from 'outstatic'

export interface HomeFields {
  heroTitle?: string
  heroSubtitle?: string
}

export interface Home extends OstDocument<HomeFields> {}

export type HomeField = keyof Home
