// Generated by Outstatic - do not edit manually
import type { OstDocument } from 'outstatic'

export interface MusicFields {
  bannerImage?: string
  bannerLabel?: string
  pageTitle?: string
  pageSubtitle?: string
}

export interface Music extends OstDocument<MusicFields> {}

export type MusicField = keyof Music
