// Generated by Outstatic - do not edit manually
// This file provides typed overloads for Outstatic server functions

import type { CollectionName, CollectionDocument, SingletonName, SingletonDocument, AllDocuments } from './collections'
import type { EventsFields } from './events'
import type { MembersFields } from './members'
import type { NavigationFields } from './navigation'
import type { TracksFields } from './tracks'
import type { AboutFields } from './_singletons/about'
import type { ContactFields } from './_singletons/contact'
import type { EventsFields } from './_singletons/events'
import type { HomeFields } from './_singletons/home'
import type { MusicFields } from './_singletons/music'
import type { OutstaticSchema } from 'outstatic'
import type { Query } from 'sift'

/** Fluent API for querying documents */
interface FindAPI<T, P = T> {
  /** Sort results by field(s) */
  sort(sort: { [K in keyof T]?: 1 | -1 } | (keyof T)[] | keyof T): FindAPI<T, P>
  /** Select fields to return (use 'as const' for type narrowing) */
  project<K extends keyof T>(projection: readonly K[]): FindAPI<T, Pick<T, K>>
  project(projection: Record<string, number>): FindAPI<T, Partial<T>>
  /** Skip N results */
  skip(skip: number): FindAPI<T, P>
  /** Limit to N results */
  limit(limit: number): FindAPI<T, P>
  /** Get first result */
  first(): Promise<P | undefined>
  /** Get all results as array */
  toArray(): Promise<P[]>
}

/** Infers the document type from a query's collection property */
type InferDocumentType<Q> =
  Q extends { collection: 'events' } ? OutstaticSchema<EventsFields> :
  Q extends { collection: 'members' } ? OutstaticSchema<MembersFields> :
  Q extends { collection: 'navigation' } ? OutstaticSchema<NavigationFields> :
  Q extends { collection: 'tracks' } ? OutstaticSchema<TracksFields> :
  OutstaticSchema<AllDocuments>

/** API returned by load() */
interface LoadAPI {
  /** Find events documents with field projection (use 'as const' for type narrowing) */
  find<K extends keyof OutstaticSchema<EventsFields>>(
    query: { collection: 'events' } & Record<string, unknown>,
    projection: readonly K[]
  ): FindAPI<OutstaticSchema<EventsFields>, Pick<OutstaticSchema<EventsFields>, K>>

  /** Find events documents */
  find(
    query: { collection: 'events' } & Record<string, unknown>,
    projection: string[]
  ): FindAPI<OutstaticSchema<EventsFields>>

  /** Find events documents */
  find(
    query: { collection: 'events' } & Record<string, unknown>,
    projection?: { [key: string]: number }
  ): FindAPI<OutstaticSchema<EventsFields>>

  /** Find members documents with field projection (use 'as const' for type narrowing) */
  find<K extends keyof OutstaticSchema<MembersFields>>(
    query: { collection: 'members' } & Record<string, unknown>,
    projection: readonly K[]
  ): FindAPI<OutstaticSchema<MembersFields>, Pick<OutstaticSchema<MembersFields>, K>>

  /** Find members documents */
  find(
    query: { collection: 'members' } & Record<string, unknown>,
    projection: string[]
  ): FindAPI<OutstaticSchema<MembersFields>>

  /** Find members documents */
  find(
    query: { collection: 'members' } & Record<string, unknown>,
    projection?: { [key: string]: number }
  ): FindAPI<OutstaticSchema<MembersFields>>

  /** Find navigation documents with field projection (use 'as const' for type narrowing) */
  find<K extends keyof OutstaticSchema<NavigationFields>>(
    query: { collection: 'navigation' } & Record<string, unknown>,
    projection: readonly K[]
  ): FindAPI<OutstaticSchema<NavigationFields>, Pick<OutstaticSchema<NavigationFields>, K>>

  /** Find navigation documents */
  find(
    query: { collection: 'navigation' } & Record<string, unknown>,
    projection: string[]
  ): FindAPI<OutstaticSchema<NavigationFields>>

  /** Find navigation documents */
  find(
    query: { collection: 'navigation' } & Record<string, unknown>,
    projection?: { [key: string]: number }
  ): FindAPI<OutstaticSchema<NavigationFields>>

  /** Find tracks documents with field projection (use 'as const' for type narrowing) */
  find<K extends keyof OutstaticSchema<TracksFields>>(
    query: { collection: 'tracks' } & Record<string, unknown>,
    projection: readonly K[]
  ): FindAPI<OutstaticSchema<TracksFields>, Pick<OutstaticSchema<TracksFields>, K>>

  /** Find tracks documents */
  find(
    query: { collection: 'tracks' } & Record<string, unknown>,
    projection: string[]
  ): FindAPI<OutstaticSchema<TracksFields>>

  /** Find tracks documents */
  find(
    query: { collection: 'tracks' } & Record<string, unknown>,
    projection?: { [key: string]: number }
  ): FindAPI<OutstaticSchema<TracksFields>>

  /** Find documents with field projection (use 'as const' for type narrowing) */
  find<K extends keyof OutstaticSchema<AllDocuments>>(
    query: Record<string, unknown>,
    projection: readonly K[]
  ): FindAPI<OutstaticSchema<AllDocuments>, Pick<OutstaticSchema<AllDocuments>, K>>

  /** Find documents matching a query */
  find(
    query: Record<string, unknown>,
    projection: string[]
  ): FindAPI<OutstaticSchema<AllDocuments>>

  /** Find documents matching a query */
  find(
    query: Record<string, unknown>,
    projection?: { [key: string]: number }
  ): FindAPI<OutstaticSchema<AllDocuments>>

  /** Find documents with explicit return type */
  find<T>(
    query: Record<string, unknown>,
    projection?: string[] | { [key: string]: number }
  ): FindAPI<T>
}

declare module 'outstatic/server' {
  /**
   * Get all documents from a collection
   * @param collection - The collection name
   * @param fields - Optional array of fields to include (use 'as const' for type narrowing)
   */
  export function getDocuments<
    C extends CollectionName,
    F extends readonly (keyof CollectionDocument<C>)[] | undefined = undefined
  >(
    collection: C,
    fields?: F
  ): F extends readonly (keyof CollectionDocument<C>)[]
    ? Pick<CollectionDocument<C>, F[number]>[]
    : CollectionDocument<C>[]

  /**
   * Get a single document by its slug
   * @param collection - The collection name
   * @param slug - The document slug
   * @param fields - Optional array of fields to include (use 'as const' for type narrowing)
   */
  export function getDocumentBySlug<
    C extends CollectionName,
    F extends readonly (keyof CollectionDocument<C>)[] | undefined = undefined
  >(
    collection: C,
    slug: string,
    fields?: F
  ): F extends readonly (keyof CollectionDocument<C>)[]
    ? Pick<CollectionDocument<C>, F[number]> | null
    : CollectionDocument<C> | null

  /**
   * Get all document slugs from a collection
   * @param collection - The collection name
   */
  export function getDocumentSlugs(collection: CollectionName): string[]

  /**
   * Get document paths for static generation
   * @param collection - The collection name
   */
  export function getDocumentPaths(collection: CollectionName): { params: { slug: string } }[]

  /**
   * Get a singleton by its slug
   * @param slug - The singleton slug
   * @param fields - Optional array of fields to include (use 'as const' for type narrowing)
   */
  export function getSingletonBySlug<
    S extends SingletonName,
    F extends readonly (keyof SingletonDocument<S>)[] | undefined = undefined
  >(
    slug: S,
    fields?: F
  ): F extends readonly (keyof SingletonDocument<S>)[]
    ? Pick<SingletonDocument<S>, F[number]> | null
    : SingletonDocument<S> | null

  /**
   * Get all singleton slugs
   */
  export function getSingletonSlugs(): SingletonName[]

  /**
   * Load the metadata database for advanced querying
   * @returns LoadAPI with typed find method that narrows based on collection query
   */
  export function load(): Promise<LoadAPI>
}
