// Generated by Outstatic - do not edit manually

import type { Events, EventsFields } from './events'
import type { Members, MembersFields } from './members'
import type { Navigation, NavigationFields } from './navigation'
import type { Tracks, TracksFields } from './tracks'
import type { About, AboutFields } from './_singletons/about'
import type { Contact, ContactFields } from './_singletons/contact'
import type { Events, EventsFields } from './_singletons/events'
import type { Home, HomeFields } from './_singletons/home'
import type { Music, MusicFields } from './_singletons/music'

export type CollectionName = 'events' | 'members' | 'navigation' | 'tracks'

export type SingletonName = 'about' | 'contact' | 'events' | 'home' | 'music'

export interface Collections {
  'events': Events
  'members': Members
  'navigation': Navigation
  'tracks': Tracks
}

export interface Singletons {
  'about': About
  'contact': Contact
  'events': Events
  'home': Home
  'music': Music
}

export type CollectionDocument<C extends CollectionName> = Collections[C]
export type SingletonDocument<S extends SingletonName> = Singletons[S]

/** Union of all document field types for use with load() */
export type AllDocuments = EventsFields | MembersFields | NavigationFields | TracksFields | AboutFields | ContactFields | EventsFields | HomeFields | MusicFields
