// Generated by Outstatic - do not edit manually
import type { OstDocument } from 'outstatic'

export interface EventsFields {
  title?: string
  date?: string
  location?: string
  description?: string
  order?: number
}

export interface Events extends OstDocument<EventsFields> {}

export type EventsField = keyof Events
