// Generated by Outstatic - do not edit manually
import type { OstDocument } from 'outstatic'

export interface MembersFields {
  name?: string
  voice?: string
  image?: string
  bio?: string
  website?: string
  websiteLabel?: string
  order?: number
}

export interface Members extends OstDocument<MembersFields> {}

export type MembersField = keyof Members
