// Generated by Outstatic - do not edit manually
import type { OstDocument } from 'outstatic'

export interface NavigationFields {
  title?: string
  href?: string
  openInNewTab?: boolean
  order?: number
}

export interface Navigation extends OstDocument<NavigationFields> {}

export type NavigationField = keyof Navigation
