// Generated by Outstatic - do not edit manually
import type { OstDocument } from 'outstatic'

export interface TracksFields {
  title?: string
  description?: string
  audioFile?: string
  externalLabel?: string
  externalHref?: string
  order?: number
}

export interface Tracks extends OstDocument<TracksFields> {}

export type TracksField = keyof Tracks
